REM.Web/Models/ErrorViewModel.cs
using System;
using Newtonsoft.Json;

namespace REM.Web.Models
{
    public class ErrorViewModel
    {
        public int Code { get; set; }
       
        public string Message { get; set; }

        public override string ToString()
        {
            return JsonConvert.SerializeObject(this);
        }
    }
}

REM.Web/Models/LandViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.Rendering;
using REM.Data.Models;

namespace REM.Web.Models
{
    public partial class LandViewModel
    {
        public LandViewModel()
        {
            LandlordItems = new List<SelectListItem>();
        }

        public long LandId { get; set; }

        [Required(ErrorMessage = "وارد کردن {0} الزامی است")]
        [Display(Name = "نام ملک")]
        public string LandName { get; set; }

        [Display(Name = "کد ملک")]
        public string LandCode { get; set; }

        [Display(Name = "نشانی ملک")]
        public string LandAddress { get; set; }

        [Display(Name = "مساحت")]
        public int Area { get; set; }

        [Display(Name = "ملک شمالی است")]
        public bool IsNorthern { get; set; }

        [Display(Name = "نام مالک")]
        public string LandlordName { get; set; }

        [Display(Name = "تلفن مالک")]
        public string LandlordCellphone { get; set; }

        public List<SelectListItem> LandlordItems { get; set; }

        [Display(Name = "نام مالک")]
        [Required(ErrorMessage = "وارد کردن {0} الزامی است")]
        [Range(1, int.MaxValue)]
        public long LandlordId { get; set; }
    }

    public partial class LandViewModel
    {
        public Land Fill()
        {
            return new Land
            {
                Address = LandAddress,
                Area = Area,
                Code = LandCode,
                IsNorthern = IsNorthern,
                Name = LandName,
            };
        }

        public void Fill(Land land)
        {
            LandId = land.ID;
            LandAddress = land.Address;
            Area = land.Area;
            LandCode = land.Code;
            IsNorthern = land.IsNorthern;
            LandName = land.Name;
            LandlordName = land.Landlord?.FirstName + " " + land.Landlord?.LastName;
            LandlordCellphone = land.Landlord?.Cellphone;
            LandlordId = land.Landlord?.ID ?? 0;
        }
    }
}

REM.Web/Controllers/LandController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using REM.Data.Models;
using REM.Service.IServices;
using REM.Web.Models;

namespace REM.Web.Controllers
{
    public class LandController : Controller
    {
        private readonly ILandService _landService;
        private readonly ILandlordService _landlordService;

        public LandController(ILandlordService landlordService, ILandService landService)
        {
            _landlordService = landlordService;
            _landService = landService;
        }

        // GET: LandController
        public ActionResult Index()
        {
            List<LandViewModel> model = new List<LandViewModel>();
            var landList = _landService.Where(x=>true,new[] {"Landlord"}).ToList();
            model = landList.Select(x => new LandViewModel()
            {
                LandlordId = x.Landlord?.ID ?? 0,
                Area = x.Area,
                IsNorthern = x.IsNorthern,
                LandAddress = x.Address ?? "",
                LandCode = x.Code ?? "",
                LandId = x.ID,
                LandName = x.Name,
                LandlordCellphone = x.Landlord?.Cellphone ?? "",
                LandlordName = x.Landlord?.FirstName + " " + x.Landlord?.LastName
            }).ToList();
            return View(model);
        }

        // GET: LandController/Details/5
        public ActionResult Details(int id)
        {
            var land = _landService.Where(x => x.ID == id, new[] { "Landlord" }).SingleOrDefault();
            LandViewModel model = new LandViewModel();
            model.Fill(land);
            var landlordList = _landlordService.GetAll().ToList();
            model.LandlordItems = landlordList.Select(x => new SelectListItem
            {
                Text = x.FirstName + " " + x.LastName,
                Value = x.ID.ToString()
            }).ToList();

            return View(model);
        }

        // GET: LandController/Create
        public ActionResult Create()
        {
            var landlordList = _landlordService.GetAll().ToList();
            LandViewModel model = new LandViewModel
            {
                LandlordItems = landlordList.Select(x => new SelectListItem
                {
                    Text = x.FirstName + " " + x.LastName,
                    Value = x.ID.ToString()
                }).ToList()
            };
            return View(model);
        }

        // POST: LandController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(LandViewModel model)
        {
            try
            {
                Land land = model.Fill();
                var landlord = _landlordService.Get(model.LandlordId);
                land.Landlord = landlord;
                _landService.Insert(land);
                return new JsonResult(new
                {
                    code = 200,
                   location = ""
                });
            }
            catch (Exception exception)
            {
                return new JsonResult(new
                {
                    code = 1,
                    message = "خطا در پردازش درخواست"
                });
            }
        }

        // GET: LandController/Edit/5
        public ActionResult Edit(int id)
        {
            var land = _landService.Where(x => x.ID == id, new[] { "Landlord" }).SingleOrDefault();
            LandViewModel model = new LandViewModel();
            model.Fill(land);
            var landlordList = _landlordService.GetAll().ToList();
            model.LandlordItems = landlordList.Select(x => new SelectListItem
            {
                Text = x.FirstName + " " + x.LastName,
                Value = x.ID.ToString()
            }).ToList();

            return View(model);
        }

        // POST: LandController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id,LandViewModel model)
        {
            try
            {
                var land = _landService.Get(id);
                land.Address = model.LandAddress;
                land.Area = model.Area;
                land.Code = model.LandCode;
                land.IsNorthern = model.IsNorthern;
                land.Name = model.LandName;
                _landService.Update(land);
                return new JsonResult(new
                {
                    code = 200,
                    location = ""
                });
            }
            catch
            {
                return new JsonResult(new
                {
                    code = 1,
                    message = "خطا در پردازش درخواست"
                });
            }
        }

        // GET: LandController/Delete/5
        public ActionResult Delete(int id)
        {
            var land = _landService.Where(x => x.ID == id, new[] { "Landlord" }).SingleOrDefault();
            LandViewModel model = new LandViewModel();
            model.Fill(land);
            var landlordList = _landlordService.GetAll().ToList();
            model.LandlordItems = landlordList.Select(x => new SelectListItem
            {
                Text = x.FirstName + " " + x.LastName,
                Value = x.ID.ToString()
            }).ToList();

            return View(model);
        }

        // POST: LandController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, LandViewModel model)
        {
            try
            {
                _landService.Delete(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(model);
            }
        }
    }
}

REM.Web/Views/Land/Create.cshtml
@model REM.Web.Models.LandViewModel

@{
    ViewData["Title"] = "Create";
}

<style>
    .filter-option-inner-inner, .dropdown-menu {
        text-align: right !important;
    }
</style>
<h4>ثبت ملک</h4>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Create" id="createLand">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <div class="row">
                    <label asp-for="LandName" class="control-label col-md-2"></label>
                    <input asp-for="LandName" class="form-control col-md-7" />
                    <span asp-validation-for="LandName" class="text-danger col-md-3"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <label asp-for="LandCode" class="control-label col-md-2"></label>
                    <input asp-for="LandCode" class="form-control col-md-7" />
                    <span asp-validation-for="LandCode" class="text-danger col-md-3"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <label asp-for="Area" class="control-label col-md-2"></label>
                    <input asp-for="Area" class="form-control col-md-7" />
                    <span asp-validation-for="Area" class="text-danger col-md-3"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <label asp-for="LandlordId" class="control-label col-md-2"></label>
                    <select asp-for="LandlordId" asp-items="@(new SelectList(Model.LandlordItems, "Value", "Text"))"
                            class="form-control col-md-7 selectpicker" title="لطفا انتخاب کنید" data-live-search="true">
                    </select>
                    <span asp-validation-for="LandlordId" class="text-danger col-md-3"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <label asp-for="LandAddress" class="control-label col-md-2"></label>
                    <textarea asp-for="LandAddress" class="form-control col-md-7"></textarea>
                    <span asp-validation-for="LandAddress" class="text-danger col-md-3"></span>
                </div>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsNorthern" /> @Html.DisplayNameFor(model => model.IsNorthern)
                </label>
            </div>
            
        </form>
    </div>
</div>
<div class="form-group">
    <button onclick="submitForm('createLand')" class="btn btn-success">ثبت</button>
</div>
<div>
    <a asp-action="Index">بازگشت به لیست</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
        $(document).ready(function () {
            $('.selectpicker').selectpicker({
                liveSearch: true,
                maxOptions: 1
            });
        })
    </script>
}

REM.Web/Views/Land/Delete.cshtml
@model REM.Web.Models.LandViewModel

@{
    ViewData["Title"] = "Delete";
}

<h3>حذف ملک</h3>

<h4>آیا از حذف این ملک اطمینان دارید؟</h4>
<div>
    <hr />
    <div class="row">
        <div class="col-sm-2">
            <b>
                @Html.DisplayNameFor(model => model.LandName)
            </b>
        </div>
        <div class="col-sm-10">
            @Html.DisplayFor(model => model.LandName)
        </div>
        <div class="col-sm-2">
            <b>
                @Html.DisplayNameFor(model => model.LandCode)
            </b>
        </div>
        <div class="col-sm-10">
            @Html.DisplayFor(model => model.LandCode)
        </div>
        <div class="col-sm-2">
            <b>
                @Html.DisplayNameFor(model => model.LandAddress)
            </b>
        </div>
        <div class="col-sm-10">
            @Html.DisplayFor(model => model.LandAddress)
        </div>
        <div class="col-sm-2">
            <b>
                @Html.DisplayNameFor(model => model.Area)
            </b>
        </div>
        <div class="col-sm-10">
            @Html.DisplayFor(model => model.Area)
        </div>
        <div class="col-sm-2">
            <b>
                @Html.DisplayNameFor(model => model.IsNorthern)
            </b>
        </div>
        <div class="col-sm-10">
            @Html.DisplayFor(model => model.IsNorthern)
        </div>
        <div class="col-sm-2">
            <b>
                @Html.DisplayNameFor(model => model.LandlordName)
            </b>
        </div>
        <div class="col-sm-10">
            @Html.DisplayFor(model => model.LandlordName)
        </div>
        <div class="col-sm-2">
            <b>
                @Html.DisplayNameFor(model => model.LandlordCellphone)
            </b>
        </div>
        <div class="col-sm-10">
            @Html.DisplayFor(model => model.LandlordCellphone)
        </div>
    </div>

    <form asp-action="Delete">
        <input type="submit" value="حذف" class="btn btn-danger" />
        <br/>
        <a asp-action="Index">بازگشت به لیست</a>
    </form>
</div>

REM.Web/Views/Land/Details.cshtml
@model REM.Web.Models.LandViewModel

@{
    ViewData["Title"] = "Details";
}

<h3>جزئیات ملک</h3>

<div>
    <hr />
    <div class="row">
        <div class="col-sm-2">
            <b>
                @Html.DisplayNameFor(model => model.LandName)
            </b>
        </div>
        <div class="col-sm-10">
            @Html.DisplayFor(model => model.LandName)
        </div>
        <div class="col-sm-2">
            <b>
                @Html.DisplayNameFor(model => model.LandCode)
            </b>
        </div>
        <div class="col-sm-10">
            @Html.DisplayFor(model => model.LandCode)
        </div>
        <div class="col-sm-2">
            <b>
                @Html.DisplayNameFor(model => model.LandAddress)
            </b>
        </div>
        <div class="col-sm-10">
            @Html.DisplayFor(model => model.LandAddress)
        </div>
        <div class="col-sm-2">
            <b>
                @Html.DisplayNameFor(model => model.Area)
            </b>
        </div>
        <div class="col-sm-10">
            @Html.DisplayFor(model => model.Area)
        </div>
        <div class="col-sm-2">
            <b>
                @Html.DisplayNameFor(model => model.IsNorthern)
            </b>
        </div>
        <div class="col-sm-10">
            @Html.DisplayFor(model => model.IsNorthern)
        </div>
        <div class="col-sm-2">
            <b>
                @Html.DisplayNameFor(model => model.LandlordName)
            </b>
        </div>
        <div class="col-sm-10">
            @Html.DisplayFor(model => model.LandlordName)
        </div>
        <div class="col-sm-2">
            <b>
                @Html.DisplayNameFor(model => model.LandlordCellphone)
            </b>
        </div>
        <div class="col-sm-10">
            @Html.DisplayFor(model => model.LandlordCellphone)
        </div>
    </div>

</div>
<div>
    @Html.ActionLink("ویرایش", "Edit", new { id = Model.LandId }) 
    <br/>
    <a asp-action="Index">Back to List</a>
</div>

REM.Web/Views/Land/Edit.cshtml
@model REM.Web.Models.LandViewModel

@{
    ViewData["Title"] = "Edit";
}

<style>
    .filter-option-inner-inner, .dropdown-menu {
        text-align: right !important;
    }
</style>

<h1>ویرایش ملک</h1>

<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Edit" id="editLand">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <div class="row">
                    <label asp-for="LandName" class="control-label col-md-2"></label>
                    <input asp-for="LandName" class="form-control col-md-7" />
                    <span asp-validation-for="LandName" class="text-danger col-md-3"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <label asp-for="LandCode" class="control-label col-md-2"></label>
                    <input asp-for="LandCode" class="form-control col-md-7" />
                    <span asp-validation-for="LandCode" class="text-danger col-md-3"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <label asp-for="Area" class="control-label col-md-2"></label>
                    <input asp-for="Area" class="form-control col-md-7" />
                    <span asp-validation-for="Area" class="text-danger col-md-3"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <label asp-for="LandlordId" class="control-label col-md-2"></label>
                    <select asp-for="LandlordId" asp-items="@(new SelectList(Model.LandlordItems, "Value", "Text"))"
                            class="form-control col-md-7 selectpicker" title="لطفا انتخاب کنید" data-live-search="true">
                    </select>
                    <span asp-validation-for="LandlordId" class="text-danger col-md-3"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <label asp-for="LandAddress" class="control-label col-md-2"></label>
                    <textarea asp-for="LandAddress" class="form-control col-md-7"></textarea>
                    <span asp-validation-for="LandAddress" class="text-danger col-md-3"></span>
                </div>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsNorthern" /> @Html.DisplayNameFor(model => model.IsNorthern)
                </label>
            </div>
        </form>
    </div>
</div>
<div class="form-group">
    <button onclick="submitForm('editLand')" class="btn btn-primary">ذخیره</button>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

REM.Web/Views/Land/Index.cshtml
@model IEnumerable<REM.Web.Models.LandViewModel>

@{
    ViewData["Title"] = "Index";
}

<h2>لیست ملک ها</h2>

<p>
    <a asp-action="Create" class="btn btn-primary">جدید</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.LandName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LandCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Area)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsNorthern)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LandlordName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LandlordCellphone)
            </th>
            <th>
                عملیات
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.LandName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LandCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Area)
            </td>
            <td>
                @(item.IsNorthern ? "بله" : "خیر" )
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LandlordName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LandlordCellphone)
            </td>
            <td>
                @Html.ActionLink("ویرایش", "Edit", new { id=item.LandId }) |
                @Html.ActionLink("جزئیات", "Details", new { id = item.LandId }) |
                @Html.ActionLink("حذف", "Delete", new { id = item.LandId })
            </td>
        </tr>
}
    </tbody>
</table>

REM.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - REM.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/lib/bootstrap-select/css/bootstrap-select.css" rel="stylesheet" />
</head>
<body dir="rtl">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Land" asp-action="Index">صفحه اصلی</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @*<div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>*@
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - REM.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap-select/js/bootstrap-select.js"></script>
    <script src="~/lib/bootstrap-select/js/i18n/defaults-fa_IR.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>